create table public.section_group (
                               id int8 generated by default as identity,
                               created_date timestamp,
                               status varchar(255),
                               updated_date timestamp,
                               name varchar(255) not null,
                               primary key (id)
);

-- added group
INSERT INTO public.section_group (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Медные кабели');
INSERT INTO public.section_group (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'ВОК Кабели');
INSERT INTO public.section_group (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Кабельная инфруструктура');
INSERT INTO public.section_group (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Оборудование');



-- alter table public.material ADD COLUMN group_id int8;

