alter table estimate add order_id int8;
alter table estimate add simple_text varchar(2048);
alter table orders alter column version_estimate type varchar(255);

alter table if exists estimate add constraint FK_estimate_orders foreign key (order_id) references orders;

update estimate set order_id = orders.id from orders where estimate.ext_id = orders.ext_id;
update orders set version_estimate = 'PROCESS' from estimate;

alter table estimate add amount float8 default 0.00;

alter table estimate_devices add id int8 generated by default as identity;
alter table estimate_devices add constraint estimate_devices_pk primary key (id);
alter table estimate_devices add quantity int4 default 0;
alter table estimate_devices drop constraint if exists fk_devices_estimate cascade;

alter table estimate_materials add id int8 generated by default as identity;
alter table estimate_materials add constraint estimate_materials_pk primary key (id);
alter table estimate_materials add quantity int4 default 0;
alter table estimate_materials drop constraint if exists fk_materials_estimate cascade;

alter table estimate_works add id int8 generated by default as identity;
alter table estimate_works add constraint estimate_works_pk primary key (id);
alter table estimate_works add quantity int4 default 0;
alter table estimate_works drop constraint if exists fk_works_estimate cascade;