
-- TABLE
create table public.department (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    name varchar(255) not null,
    primary key (id)
);

create table public.device (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    dimension varchar(255) not null,
    name varchar(255) not null,
    note varchar(2048),
    price float8 not null,
    primary key (id)
);

create table public.devices_departments (
    device_id int8 not null,
    department_id int8 not null
);

create table public.estimate (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    address varchar(2048),
    customer varchar(2048),
    ext_id varchar(255),
    work_description varchar(2048),
    author_id int8,
    department_id int8,
    primary key (id)
);

create table public.estimate_devices (
    estimate_id int8 not null,
    devices_id int8 not null
);

create table public.estimate_materials (
    estimate_id int8 not null,
    materials_id int8 not null
);

create table public.estimate_works (
    estimate_id int8 not null,
    works_id int8 not null
);

create table public.material (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    dimension varchar(255) not null,
    name varchar(255) not null,
    note varchar(2048),
    price float8 not null,
    primary key (id)
);

create table public.materials_departments (
    material_id int8 not null,
    department_id int8 not null
);

create table public.orders (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    address varchar(255),
    customer varchar(255),
    ext_id varchar(255),
    verification_date timestamp,
    author_id int8,
    department_id int8,
    verification_name_id int8,
    primary key (id)
);

create table public.position_users (
    users_id int8 not null,
    position_id int8 not null
);

create table public.positions (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    name varchar(255) not null,
    primary key (id)
);

create table public.roles (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    roles varchar(255) not null,
    primary key (id)
);

create table public.users (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255) not null,
    updated_date timestamp,
    email varchar(255) unique not null check ( email != '' ),
    first_name varchar(255) not null check ( first_name != '' ),
    last_name varchar(255) not null check ( last_name != '' ),
    password varchar(255) not null check ( password != '' ),
    username varchar(255) unique not null check ( username != '' ),
    department_id int8 not null,
    primary key (id)
);

create table public.users_roles (
    user_id int8 not null,
    role_id int8 not null
);

create table public.work (
    id int8 generated by default as identity,
    created_date timestamp,
    status varchar(255),
    updated_date timestamp,
    dimension varchar(255) not null,
    name varchar(255) not null,
    note varchar(2048),
    price float8 not null,
    primary key (id)
);

create table public.works_departments (
    work_id int8 not null,
    department_id int8 not null
);

-- FK
alter table if exists devices_departments add constraint FK_device_departments foreign key (department_id) references department;
alter table if exists devices_departments add constraint FK_departments_device foreign key (device_id) references device;

alter table if exists estimate add constraint FK_estimate_author foreign key (author_id) references users;
alter table if exists estimate add constraint FK_estimate_departments foreign key (department_id) references department;

alter table if exists estimate_devices add constraint FK_estimate_devices foreign key (devices_id) references device;
alter table if exists estimate_devices add constraint FK_devices_estimate foreign key (estimate_id) references estimate;

alter table if exists estimate_materials add constraint FK_estimate_materials foreign key (materials_id) references material;
alter table if exists estimate_materials add constraint FK_materials_estimate foreign key (estimate_id) references estimate;

alter table if exists estimate_works add constraint FK_estimate_works foreign key (works_id) references work;
alter table if exists estimate_works add constraint FK_works_estimate foreign key (estimate_id) references estimate;

alter table if exists materials_departments add constraint FK_materials_department foreign key (department_id) references department;
alter table if exists materials_departments add constraint FK_department_materials foreign key (material_id) references material;

alter table if exists orders add constraint FK_order_author foreign key (author_id) references users;
alter table if exists orders add constraint FK_orders_departments foreign key (department_id) references department;
alter table if exists orders add constraint FK_orders_verification_name foreign key (verification_name_id) references users;

alter table if exists position_users add constraint FK_user_positions foreign key (position_id) references positions;
alter table if exists position_users add constraint FK_position_users foreign key (users_id) references users;

alter table if exists users add constraint FK_users_department foreign key (department_id) references department;

alter table if exists users_roles add constraint FK_users_roles foreign key (role_id) references roles;
alter table if exists users_roles add constraint FK_roles_users foreign key (user_id) references users;

alter table if exists works_departments add constraint FK_work_departments foreign key (department_id) references department;
alter table if exists works_departments add constraint FK_departments_work foreign key (work_id) references work;




-- added departments
INSERT INTO public.department (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Отдел эксплуатации сети');
INSERT INTO public.department (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Отдел развития транспортной сети');


-- create user
INSERT INTO public.users (username, first_name, last_name, email, password, created_date, updated_date, status, department_id) VALUES ('artem', 'Артем', 'Савельев', 'test@test.com', '$2y$12$3mufhhEhusW.Ccyx60xKq.5ncQUAXT3G9Xg/KyQU8vKogpR7nj2qW', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', 1);


-- create roles
INSERT INTO public.roles (roles, created_date, updated_date, status) VALUES ('ROLE_USER', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE');
INSERT INTO public.roles (roles, created_date, updated_date, status) VALUES ('ROLE_ADMIN', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE');
INSERT INTO public.roles (roles, created_date, updated_date, status) VALUES ('ROLE_SUPERUSER', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE');

-- FK users roles
INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO public.users_roles (user_id, role_id) VALUES (1, 3);


-- create positions
INSERT INTO public.positions (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Старший инженер');
INSERT INTO public.positions (created_date, status, updated_date, name) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'Начальник');

INSERT INTO public.position_users (users_id, position_id) VALUES (1, 2);

-- added device
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Маршрутизатор Mikrotik RB952Ui-5AC2nd', 'Wi-Fi', 4000);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Маршрутизатор Mikrotik RB750Gr3', '', 5000);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Точка доступа Unifi AP AC Lite', '', 7000);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутатор D-Link DES-3200-28', '', 13450);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'ИБП Eaton PW9130T1000', '', 15933);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'ИБП Inelt 800RM1U', '', 18861);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Карта управления для Eaton', '', 15933);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Карта управления для Inelt', '', 13447);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутатор TP-Link TL-SF1016D', '', 2000);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутатор TP-Link TL-SF1008D', '', 1000);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-1M.IP', '1xFXS, 1xWAN, 2xLAN, 1xUSB, SIP', 3078);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-2M.IP', '2xFXS, 1xWAN, 1xLAN, 1xUSB, SIP', 3264);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-4.IP', '4xFXS, 1xWAN, 1xUSB, SIP', 8964);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-8.IP', '8xFXS, 1xWAN, 1xUSB, SIP', 12650);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-16.IP', '16хFXS, 3хRJ45-10/100/1000, H.248 (MEGACO), 1U, AC 220V', 28880);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-24.IP', '24хFXS, 2хRJ45-10/100/1000, SIP/H.323, 1U, AC 220V', 39130);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шасси Eltex TAU-32M.IP-M', 'VoIP-шлюз TAU-32M.IP: 4 слота для субмодулей TAU32M-M8S или TAU32M-M8O, 3хRJ-45 (LAN), 2 шасси под SFP, 1 слот для блока питания PM150-220/12 или PM75-48/12, 1U, H.248', 25647);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Блок Eltex TAU32M-M8O', 'Cубмодуль абонентских линий АТС (устанавливается в шасси TAU-32M.IP): 8 аналоговых портов (FXO)', 13985);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Блок Eltex TAU32M-M8S', 'Cубмодуль абонентских комплектов (устанавливается в шасси TAU-32M.IP): 8 аналоговых абонентских портов (FXS)', 8390);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-36.IP', '36хFXS, 3хRJ45-10/100/1000, 2 слота для SFP, 1U, AC 220V', 63870);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шлюз VoiceIP Eltex TAU-72.IP', '72хFXS, 3хRJ45-10/100/1000, 2 слота для SFP, 1U, AC 220V', 95155);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Транковый шлюз Eltex SMG-2', '1 порт Е1 (RJ-48), 1 дополнительный порт Е1 (опционально), 64 VoIP-канала, 1 порт 10/100/1000Base-T (RJ-45), 1 порт USB 2.0', 33540);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Транковый шлюз Eltex SMG-4', '4 порта Е1 (RJ-48), 128 VoIP-каналов, 1 порт 10/100/1000Base-T (RJ-45), 1 порт USB 2.0', 58700);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Транковый шлюз Eltex SMG-1016M', '4 слота для субмодулей М4Е1, 6 слотов для субмодулей SM-VP-M300, 2 слота для модулей питания PM160-220/12 и PM75-48/12', 118270);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Транковый шлюз Eltex SMG-2016', '4 слота для субмодулей М4Е1, 6 слотов для субмодулей SM-VP-M300, 2 слота для модулей питания PM160-220/12 и PM75-48/12', 199380);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Субмодуль с поддержкой до 4-х потоков Е1 Eltex M4E1', 'Субмодуль M4E1 устанавливается в транковые шлюзы SMG-1016M и SMG-2016. Предназначен для обработки потоков E1', 15940);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Субмодуль VoIP, до 128 каналов SIP Eltex SM-VP-M300', 'Субмодуль SM-VP-M300 устанавливается в транковые шлюзы SMG-1016M и SMG-2016. Предназначен для обработки голосового трафика IP телефонии', 41240);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Модуль питания 48V DC, 100W Eltex PM100-48/12', 'Модуль питания 48V AC, 100W', 5990);
INSERT INTO public.device (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Модуль питания 220V AC, 160W Eltex PM160-220/12', 'Модуль питания 220V AC, 160W', 5990);


-- FK device department
INSERT INTO public.devices_departments (device_id, department_id) VALUES (1, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (2, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (3, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (4, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (5, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (6, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (7, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (8, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (9, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (10, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (11, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (12, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (13, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (14, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (15, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (16, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (17, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (18, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (19, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (20, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (21, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (22, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (23, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (24, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (25, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (26, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (27, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (28, 1);
INSERT INTO public.devices_departments (device_id, department_id) VALUES (29, 1);



-- added materials
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, LSZH, 4 пары, Cat.5е для внутренних сетей', 'По закупке 15', 19);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель FTP, 24 AWG, PVC, 4 пары, Cat.5е для внутренних сетей (экранированный)', 'категория 5е - 100 Мбит/с.', 34);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, ПЭ, 4 пары, Cat.5е (для уличной прокладки)', 'По закупке 16,39', 22);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 23 AWG, PVC/LSZH, 4 пары, Cat.6 для внутренних сетей', 'категория 6 - 1 Гигабит/с.', 54);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель F/UTP, 23 AWG, LSZH, 4 пары, Cat.6 для внутренних сетей (экранированный)', 'категория 6 - 1 Гигабит/с.', 73.9);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP,  23 AWG, ПЭ, 4 пары, Cat.6 (для уличной прокладки, черный)', 'категория 6 - 1 Гигабит/с.', 73.5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 23 AWG, PVC/LSZH, 4 пары, Cat.6A для внутренних сетей', 'категория 6A - 10 Гигабит/с до 55 метров', 59);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель F/UTP, 23 AWG, LSZH, 4 пары, Cat.6A для внутренних сетей (экранированный)', 'категория 6A - 10 Гигабит/с до 55 метров', 83.6);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель SFTP, 23 AWG, LSZH, 4 пары, Cat.7/Cat.7A для внутренних сетей (экранированный)', 'категория 7/7A - свыше 10 Гигабит/с.', 92);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, PVC/LSZH, 12 пар, Cat.5е для внутренних сетей', '', 148);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, PVC/LSZH, 16 пар, Cat.5е для внутренних сетей', '', 167);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, PVC/LSZH, 25 пар, Cat.5е для внутренних сетей', 'Цена по закупке', 200);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, PVC/LSZH, 50 пар, Cat.5е для внутренних сетей', '', 439);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, PVC/LSZH, 100 пар, Cat.5е для внутренних сетей', '', 822);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель UTP, 24 AWG, ПЭ, 25 пар, Cat.5е (для уличной прокладки, черный)', '', 220);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель волконно-оптический 2-4 ОВ, SM (без брони) ', '', 15);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель волконно-оптический 8 ОВ, SM (с тросиком/броня)', '', 35);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель волконно-оптический 16 ОВ, SM (с тросиком/броня)', '', 45);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель волконно-оптический 24 ОВ, SM (с тросиком/броня)', '', 55);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.5e, 2 метра, серый (патч-корд)', 'категория 5е - 100 Мбит/с.', 191);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.5e, 3 метра, серый (патч-корд)', 'категория 5е - 100 Мбит/с.', 246);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.5e, 5 метров, серый (патч-корд)', 'категория 5е - 100 Мбит/с.', 391);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.5e, 2 метра, серый (патч-корд, экран.)', 'категория 5е - 100 Мбит/с.', 237);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.5e, 3 метра, серый (патч-корд, экран.)', 'категория 5е - 100 Мбит/с.', 319);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.5e, 5 метров, серый (патч-корд, экран.)', 'категория 5е - 100 Мбит/с.', 468);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.6, 2 метра, серый (патч-корд)', 'категория 6 - 1 Гигабит/с.', 279);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.6, 3 метра, серый (патч-корд)', 'категория 6 - 1 Гигабит/с.', 333);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.6, 5 метров, серый (патч-корд)', 'категория 6 - 1 Гигабит/с.', 464);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.6, 2 метра, серый патч-корд, экран.)', 'категория 6 - 1 Гигабит/с.', 325);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.6, 3 метра, серый (патч-корд, экран.)', 'категория 6 - 1 Гигабит/с.', 440);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.6A, 2 метра, серый (патч-корд)', 'категория 6A - 10 Гигабит/с до 55 метров', 414);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 UTP Cat.6A, 3 метра, серый (патч-корд)', 'категория 6A - 10 Гигабит/с до 55 метров', 445);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.6A, 1 метр, серый (патч-корд, экран.)', 'категория 6A - 10 Гигабит/с до 55 метров', 500);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационный шнур RJ45-RJ45 S/FTP Cat.6A, 2 метра, серый (патч-корд, экран.)', 'категория 6A - 10 Гигабит/с до 55 метров', 625);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 1U, 24 порта Cat.5е, RJ45/110, T568A/B', '', 4710);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 1U, 24 порта Cat.5е, RJ45/110, T568A/B (экран.)', '', 7150);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 2U, 48 портов Cat.5е, RJ45/110, T568A/B', '', 8930);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 2U, 48 портов Cat.5е, RJ45/110, T568A/B (экран.)', '', 13484);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 1U 24 порта Cat.6, RJ45/110, T568A/B', '', 6950);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 2U 24 портов Cat.6, RJ45/110, T568A/B (экран.)', '', 11880);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 2U 48 портов Cat.6, RJ45/110, T568A/B', '', 12020);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель настенная 12 портов Cat.5e, RJ45/110, T568A/B', '', 1440);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кабельный организатор с металлическими кольцами, 19", 1U (органайзер)', '', 657);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кабельный организатор с пластиковыми кольцами и крышкой, 19", 1U (органайзер)', '', 974);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кабельный организатор с пластиковыми кольцами и крышкой, 19", 2U (органайзер)', '', 1392);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Плинт Krone LSA-PLUS 2/10 с нормально-замкнутыми (размыкаемыми) контактами на 10 пар', '', 378);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс-бокс на 30 пар (для плинтов Krone), с монтажным хомутом, с дверью, без плинтов', '', 1895);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс-бокс на 50 пар (для плинтов Krone), с монтажным хомутом, с дверью, без плинтов', '', 2520);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс-бокс на 100 пар (для плинтов Krone), с монтажным хомутом, с дверью, без плинтов', '', 3373);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама 19" для крепления 9-и плинтов типа Krone, 2U', '', 1105);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама 19" для крепления 15-и плинтов типа Krone, 3U', '', 1636);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама 19" для крепления 18-и плинтов типа Krone, 4U', '', 1951);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама (монтажный хомут) глубиной 50мм для крепления 1-го плинта типа Krone', '', 88);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама (монтажный хомут) глубиной 50мм для крепления 3-х плинтов типа Krone', '', 237);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама (монтажный хомут) глубиной 50мм для крепления 10-и плинтов типа Krone', '', 703);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 1U 110 Cat.5e, 100 пар, с коннекторами', '', 1320);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель 19" 2U 110 Cat.5e, 200 пар, с коннекторами', '', 2580);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель настенная 110 Cat.5e, 50 пар, с коннекторами', '', 760);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коммутационная панель настенная 110 Cat.5e, 100 пар, с коннекторами', '', 1090);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс оптический настенный на 4 ОВ (FC, UPC 9/125)', '', 500);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс оптический стоечный на 8 ОВ (FC, UPC 9/125)', '', 1500);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кросс оптический стоечный на 16 ОВ (FC, UPC 9/125)', '', 2500);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама монтажная настенная 19", 9U, глубина 300-400 мм', '', 2960);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рама монтажная настенная 19", 12U, глубина 300-400 мм', '', 3220);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Открытая монтажная стойка, универсальная 19", высота 1.30м, 27U, серая', '', 6260);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Открытая монтажная стойка, универсальная 19", высота 1.75м, 37U, серая', '', 7170);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Открытая монтажная стойка, универсальная 19", высота 2.20м, 45U, серая', '', 8730);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 6U, 290х600x450 мм, разборный', '', 8300);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 9U, 425x600x450 мм, разборный', '', 10390);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 12U, 560x600x450 мм, разборный', '', 11100);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 15U, 904x600x450 мм, разборный', '', 12640);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 6U 371х600х550 мм, двухсекционный со съемными боковыми стенками', '', 14520);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 9U 504х600х550 мм, двухсекционный со съемными боковыми стенками', '', 16550);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 12U, 635x600x550 мм, двухсекционный со сьёмными боковыми стенками', '', 18570);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 15U 771х600х550 мм, двухсекционный со съемными боковыми стенками', '', 20670);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф настенный 18U 904х600х550 мм, двухсекционный со съемными боковыми стенками', '', 22700);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 22U, 1050х600х600 мм, разборный, дверь со стеклом', '', 27270);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 27U, 1272х600х600 мм, разборный, дверь со стеклом', '', 30000);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 32U, 1494х600х600 мм, разборный, дверь со стеклом', '', 32730);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 37U, 1716х600х600 мм, разборный, дверь со стеклом', '', 36360);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 42U, 1938х600х600 мм, разборный, дверь со стеклом', '', 38180);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шкаф напольный 45U, 2072х600х600 мм, разборный, дверь со стеклом', '', 43630);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Крепеж для шкафов ЕМ-10 (комплект 4шт.)', '', 72);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка 8Р8С RJ-45 Cat.5e тип Krone, в корпусе на стену (белый)', '', 100);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка 8Р8С RJ-45 Cat.5e тип Krone, в корпусе на стену двойная (белый)', '', 150);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка RJ-11, в корпусе на стену (белый)', '', 50);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка RJ-11, в корпусе на стену двойная (белый)', '', 100);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone Cat.5e, RJ45/110, белый AESP серии ЕС', '', 144);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone Cat.6, RJ45/110, белый AESP серия МТ', '', 271);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone Cat.6A, RJ45/110, белый AESP', '', 260);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone экран. Cat.5e, FTP, RJ45/110 AESP серия МТ', '', 203);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone экран. Cat.6, FTP, RJ45/110 AESP', '', 379);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розеточный модуль типа Keystone экран. Cat.6A, FTP, RJ45/110 AESP', '', 405);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Вставка 25x50 мм для 2 модулей типа Keystone', '', 40);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Вставка 25x50 мм для 1 модуля типа Keystone', '', 40);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка 25х50', '', 45);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рамка Standard, для внутренней розетки горизонтальной установки, 86x86 мм', '', 49);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коннектор RJ-45 (8P8C), Cat.5e', '', 12.6);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коннектор RJ-45 (8P8C), Cat.5e, экранированный', '', 25);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коннектор RJ-11 (4P4C)', '', 2.5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Коннектор RJ-12 (6P4C)', '', 3);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', '3M Scotchlok™ (Скотчлок) UY2 — соединитель медных жил, 0,4-0,9 мм (100 штук в упаковке)', '', 4.37);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', '3M Scotchlok™ (Скотчлок) UR2 — соединитель медных жил, разветвление, 0,4-0,9 мм', '', 7.53);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', '3M Armorcast™ (Арморкаст™) - структурный материал, 1,5 м х 97 мм', '', 801.69);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', '3M Scotch™ (Скотч™) VM — лента винил-мастика, 38 мм х 6 м', '', 824.58);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'DLP Кабель-канал 50х105 с крышкой, без перегородки, 2м Legrand', '', 950);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка торцевая 50х105 Legrand', '', 93);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внутренний 50х105 Legrand', '', 469);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внешний 50х105 Legrand', '', 522);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол плоский 50х105 Legrand', '', 708);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Накладка на стык крышек 50х105 Legrand', '', 91);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Накладка на стык кабель-канала 50х105, 2шт Legrand', '', 58);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Перегородка разделительная, 2м Legrand', '', 380);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Отвод для к/к шириной 105х105 мм Legrand', '', 1323);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Отвод для к/к шириной 80х105 мм Legrand', '', 863);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рамка 2 модуля с суппортом горизонтальная, белый  (в кабель канал Legrand)', '', 125);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рамка 2 модуля с суппортом горизонтальная (с суппортом на 1 модуль), белый  (в кабель канал Legrand)', '', 563);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Рамка 1 модуль с суппортом горизонтальная, белый  (в кабель канал Legrand)', '', 395);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка компьютерная RJ45 Cat.5e одиночная, 1 модуль (в кабель канал Legrand)', '', 357);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка компьютерная RJ45 Cat.5e одиночная, 2 модуля (в кабель канал Legrand)', '', 446);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка компьютерная RJ45 Cat.6 одиночная, 1 модуль (в кабель канал Legrand)', '', 505);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Розетка компьютерная RJ45 Cat.6 одиночная, 2 модуля (в кабель канал Legrand)', '', 593);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка, 1 модуль', '', 109);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель-канал 40х20 с крышкой, без перегородки, 2м Legrand', '', 303);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внутренний 40х20 Legrand', '', 142);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внешний 40х20 Legrand', '', 142);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Отвод Т-образный 40х20 Legrand', '', 173);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол плоский 40х20 Legrand', '', 157);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка торцевая 40х20 Legrand', '', 103);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Накладка на стык кабель-канала 40х20 Legrand', '', 53);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель-канал 40х16 с крышкой, без перегородки, 2м', '', 290);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внутренний 40х16', '', 140);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внешний 40х16', '', 140);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Отвод Т-образный 40х16', '', 172);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол плоский 40х16', '', 155);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка торцевая 40х16', '', 88);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Накладка на стык кабель-канала 40х16', '', 52);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель-канал 20х12,5 с крышкой, без перегородки, 2м Legrand', '', 87);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внутренний 20х12,5 Legrand', '', 70);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол внешний 20х12,5 Legrand', '', 70);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Отвод Т-образный 20х12,5 Legrand', '', 108);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Угол плоский 20х12,5 Legrand', '', 86);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка торцевая 20х12,5 Legrand', '', 58);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Накладка на стык кабель-канала 20х12,5 Legrand', '', 32);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Кабель-канал напольный 50x12', '', 580);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Кабель-канал 40х17 белый с крышкой DKC 2 м', '', 140);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Внешний угол для кабель-канала DKC 40х17 белый', '', 38);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Внутренний угол для кабель-канала DKC 40х17 белый', '', 38);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Плоский угол для кабель-канала DKC 40х17 белый', '', 44);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Тройник для кабель-канала DKC 40х17 белый', '', 44);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Соединение на стык кабель-канала DKC 40х17 белое', '', 70);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Заглушка для кабель-канала ДКС 40х17 торцевая белая', '', 44);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Труба гофрированная 32мм 25 метров DKC', '', 25.1);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Труба гофрированная 25мм 50 метров DKC', '', 16.7);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Труба гофрированная 20мм 100 метров DKC', '', 10.4);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Труба гофрированная 16мм 100 метров DKC', '', 8.5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х50 L3000', '', 231);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х100 L3000', '', 254);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х150 L3000', '', 311);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х200 L3000', '', 341);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х300 L3000', '', 471);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 30х400 L3000', '', 663);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х50 L3000', '', 257);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х100 L3000', '', 307);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х150 L3000', '', 357);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х200 L3000', '', 387);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х300 L3000', '', 697);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 50х400 L3000', '', 804);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 100х100 L3000', '', 422);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 100х150 L3000', '', 481);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 100х200 L3000', '', 540);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 100х300 L3000', '', 839);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволочный лоток 100х400 L3000', '', 962);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Пластина для подвеса проволочного лотка на штанге', '', 67.43);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Хомут стандартный, чёрный,  3,6 х 370', '', 5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Изолента', '', 129);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Саморез 32х3.8', '', 0.5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Дюбель Sormat 6х30 NAT нейлон', '', 1.24);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтажная коробка в полые стены', '', 19);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Штанга с резьбой М10х1 м DIN 975', '', 106);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Штанга с резьбой М10х2 м DIN 975', '', 107);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Штанга с резьбой М12х1 м DIN 975', '', 91);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Штанга с резьбой М12х2 м DIN 975', '', 129);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шайбы кузовные оцинкованные 10х30 мм DIN 9021', '', 2.63);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Шайбы кузовные оцинкованные 12х37 мм DIN 9021', '', 4.53);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Гайка с фланцем DIN 6923 М10', '', 2.38);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Гайка с фланцем DIN 6923 М12', '', 3.97);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Анкер забивной стальной 10 мм', '', 16.5);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Анкер забивной стальной 12 мм', '', 33);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Муфта оптическая МОГу', '', 2200);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Комплект муфты для сращивания двух 10-парных кабелей типа ТП', '', 1911.29);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Комплект муфты для сращивания двух кабелей типа ТП парностью 20/30 пар', '', 2624.43);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Комплект муфты для сращивания двух 50-парных кабелей типа ТП', '', 3358.72);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Комплект муфты для сращивания двух 100-парных кабелей типа ТП', '', 4638.43);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Комплект муфты для разветвления кабеля типа ТП парностью 30/50 пар', '', 4026.33);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Стандартный комплект Радиостойки РС1-1900', null, 4600);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Опорная гильза ОГР-1 (для установки Радиостоек РС-1)', null, 3000);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Прокладка резиновая под стойку (100х100)', null, 50);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволока БСМ1 3мм сталемедная биметаллическая', null, 50);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Проволока БСМ1 4мм сталемедная биметаллическая', null, 70);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Траверса дополнительная РС-1', null, 500);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Изолятор ТФ-16 ', null, 80);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Трансформатор', null, 1200);
INSERT INTO public.material (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Районный узел (устанволен в антивандальный шкафной)', null, 441000);






INSERT INTO public.materials_departments (material_id, department_id) VALUES (1, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (2, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (3, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (4, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (5, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (6, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (7, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (8, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (9, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (10, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (11, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (12, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (13, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (14, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (15, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (16, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (17, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (18, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (19, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (20, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (21, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (22, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (23, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (24, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (25, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (26, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (27, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (28, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (29, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (30, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (31, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (32, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (33, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (34, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (35, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (36, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (37, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (38, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (39, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (40, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (41, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (42, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (43, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (44, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (45, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (46, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (47, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (48, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (49, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (50, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (51, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (52, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (53, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (54, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (55, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (56, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (57, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (58, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (59, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (60, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (61, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (62, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (63, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (64, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (65, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (66, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (67, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (68, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (69, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (70, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (71, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (72, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (73, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (74, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (75, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (76, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (77, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (78, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (79, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (80, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (81, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (82, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (83, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (84, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (85, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (86, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (87, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (88, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (89, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (90, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (91, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (92, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (93, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (94, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (95, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (96, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (97, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (98, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (99, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (100, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (101, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (102, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (103, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (104, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (105, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (106, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (107, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (108, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (109, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (110, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (111, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (112, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (113, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (114, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (115, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (116, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (117, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (118, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (119, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (120, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (121, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (122, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (123, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (124, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (125, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (126, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (127, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (128, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (129, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (130, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (131, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (132, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (133, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (134, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (135, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (136, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (137, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (138, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (139, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (140, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (141, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (142, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (143, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (144, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (145, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (146, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (147, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (148, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (149, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (150, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (151, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (152, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (153, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (154, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (155, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (156, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (157, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (158, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (159, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (160, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (161, 1);
INSERT INTO public.materials_departments (material_id, department_id) VALUES (162, 1);






-- added works
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Монтажно-кабельные работы (за порт) ЛВС/СКС', 'Максимальная цена для кабеля длинной от 40м и больше (до 120 для ЛВС и более для телефонной сети), в зависимости от сложности (например прокладка кабеля в гофре), может увеличиться. Учитывается "обжим RJ-45, RJ-11" или расшивка на патч-панель с одной стороны, и розетка  "RJ-45, RJ-11" или расшивка на патч-панель с другой стороны, а так же прокладка кабеля от точки "А" до точки "Б".', 1500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Монтажно-кабельные работы (за порт) ЛВС/СКС', 'Максимальная цена для кабеля длинной от 5м до 40м, в зависимости от сложности (например прокладка кабеля в гофре), может увеличиться.  Учитывается "обжим RJ-45, RJ-11" или расшивка на патч-панель с одной стороны, и розетка  "RJ-45, RJ-11" или расшивка на патч-панель с другой стороны, а так же прокладка кабеля от точки "А" до точки "Б".', 1200);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Монтажно-кабельные работы (за метр)', 'По желанию. Например несложные фасадные, или внутренние работы например объединение сети. Учитывается "обжим RJ-45, RJ-11" или расшивка на патч-панель с одной стороны, и розетка  "RJ-45, RJ-11" или расшивка на патч-панель с другой стороны, а так же прокладка кабеля от точки "А" до точки "Б".', 40);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Изменение/восстановление конфигурации существующей сети (за порт) ЛВС/СКС', 'Различные изменения существующей сети. (наример поменять розетки, восстановление существующих розеток, поменять точку "свода" ЛВС, нарастить и т.д.).', 1200);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Монтаж кабель-канала', 'в зависимости от сложности и кабель-канала.', 100);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Монтаж кабельной трассы в запотолочном пространстве или на высоте', 'Например монтаж лотков, цена может быть выше в зависимости от сложности монтажа', 500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Технологическое отверстие', 'Делается с помощью перфоратора/шуруповёрта в капитальных кирпичных/бетонных/деревянных или некапитальных (межкомнатных) кирпичных/бетонных/деревянных стенах.   (D = до 32мм)', 1500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Тестирование соединения ЛВС/СКС', 'Новой, после монтажа (построенной нашими силами), в этот пункт может входить понятие "маркировка" (включаем в смету от 3-х портов)', 50);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Изготовление коммутационного шнура (патч-корд)', 'До 5 метров', 300);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Отзвон сети (существующей)', 'Отзвон существующей (уже ранее построенной, необязательно СТ) сети без изменений в конфигурацию', 500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Разработка технической документации (РП, ИД)', 'По желанию заказчика, при наличии у заказчика планировки помешений и расположения рабочих мест', 75);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м2.', 'Отрисовки планировок за м2 (при необходимости)', 'Если нет планировок у заказчика и требуется отрисовать', 7);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж в шкаф/стойку оборудования (патч-панель и др.)', '', 500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж телекоммуникационного шкафа/стойки', '', 2000);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Коммутация ЛВС/СКС в оборудование', 'Клиентское или СТ', 20);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Демонтаж телекоммуникационного шкафа/стойки', '', 2000);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Демонтаж из стойки/шкафа оборудования (патч-панель и др.)', '', 500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'порт', 'Демонтаж старой сети (за порт)', 'Если удобнее считать по портам', 500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Демонтаж старой сети (за сеть)', 'Если нет понимания сколько портов, просто демонтаж какой-либо сети (цена может быть выше в зависимости от сложности)', 5000);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж компрессионной муфты (медный кабель до 30 пар)', '', 3000);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж компрессионной муфты (медный кабель свыше 30 пар до 100 пар)', '', 5500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Монтаж кабеля связи (ВОК, медь) воздушно-кабельный переход  (за метр)', 'Выполняются кабельщиками', 90);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'м.', 'Монтаж кабеля связи (ВОК, медь) по зданию по зданию/фасаду (за метр)', 'Сложные фасадные или внутренние работы выполняются кабельщиками', 80);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж оптического кросса (до 8 волокон)', 'Выполняется отделом Супрунова', 3000);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Монтаж оптической муфты (до 8 волокон)', 'Выполняется отделом Супрунова', 3500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'шт.', 'Тестирование рефлектометром 1 волокна', 'Выполняется отделом Супрунова', 250);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'смена', 'Аренда автовышки (смена)', '', 8500);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'ед.', 'Настройка активного сетевого оборудования', 'Выполняется интернет отделом', 0);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'ед.', 'Настройка (программирование) офисной АТС до 24 портов', 'Выполняется отделом АТС', 0);
INSERT INTO public.work (created_date, status, updated_date, dimension, name, note, price) VALUES (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Moscow', 'ACTIVE', null, 'ед.', 'Настройка (программирование) офисной АТС/УПАТС свыше 24 портов', 'Выполняется отделом АТС', 0);


INSERT INTO public.works_departments (work_id, department_id) VALUES (1, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (2, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (3, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (4, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (5, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (6, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (7, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (8, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (9, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (10, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (11, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (12, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (13, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (14, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (15, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (16, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (18, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (19, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (20, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (21, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (22, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (23, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (24, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (25, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (26, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (27, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (28, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (29, 1);
INSERT INTO public.works_departments (work_id, department_id) VALUES (30, 1);

-- added orders
INSERT INTO public.orders (created_date, status, updated_date, address, customer, ext_id, verification_date, author_id, verification_name_id, department_id) VALUES ('2021-02-16 14:36:21.416745', 'ACTIVE', null, 'Цветочная ул. 25 А', 'Смарт Телеком', '1320886', null, 1, null, 1);
INSERT INTO public.orders (created_date, status, updated_date, address, customer, ext_id, verification_date, author_id, verification_name_id, department_id) VALUES ('2021-02-18 11:12:50.435036', 'ACTIVE', null, 'Энергетиков 4', 'БЦ Амбер Холл', '18022021', null, 1, null, 1);
INSERT INTO public.orders (created_date, status, updated_date, address, customer, ext_id, verification_date, author_id, verification_name_id, department_id) VALUES ('2021-02-19 11:00:16.880832', 'ACTIVE', null, 'Химиков ул. 2', 'Смарт Телеком', '1310096', null, 1, null, 1);
INSERT INTO public.orders (created_date, status, updated_date, address, customer, ext_id, verification_date, author_id, verification_name_id, department_id) VALUES ('2021-02-20 10:17:15.402780', 'ACTIVE', null, 'Коломяжский пр. 18', 'ИП Комарова Дарья Юрьевна', '1325708', null, 1, null, 1);
INSERT INTO public.orders (created_date, status, updated_date, address, customer, ext_id, verification_date, author_id, verification_name_id, department_id) VALUES ('2021-02-20 11:23:08.780922', 'ACTIVE', null, 'Самойловой ул. 7', 'Шинный альянс (абонент ВМБ)', '1324257', null, 1, null, 1);